const LessonCode = {
    ACCT3603: "Hệ thống thông tin kế toán",
    ACCT5123: "Hoạch định nguồn lực doanh nghiệp",
    ADENG1: "Tiếng Anh tăng cường 1",
    ADENG2: "Tiếng Anh tăng cường 2",
    ADENG3: "Tiếng Anh tăng cường 3",
    ADENG4: "Tiếng Anh tăng cường 4",
    AI001: "Giới thiệu ngành Trí tuệ nhân tạo",
    BOQC1: "Nhập môn máy tính lượng tử",
    BUS1125: "Khởi nghiệp kinh doanh",
    CE005: "Giới thiệu ngành Kỹ Thuật Máy tính",
    CE103: "Vi xử lý-vi điều khiển",
    CE105: "Xử lý tín hiệu số",
    CE118: "Thiết kế luận lý số",
    CE119: "Thực hành Kiến trúc máy tính",
    CE121: "Lý thuyết mạch điện",
    CE124: "Các thiết bị và mạch điện tử",
    CE201: "Đồ án 1",
    CE206: "Đồ án 2",
    CE212: "Điều khiển tự động",
    CE213: "Thiết kế hệ thống số với HDL",
    CE222: "Thiết kế vi mạch số",
    CE224: "Thiết kế hệ thống nhúng",
    CE232: "Thiết kế hệ thống nhúng không dây",
    CE303: "Robot công nghiệp",
    CE304: "Robot công nghiệp",
    CE312: "Hệ thống thời gian thực",
    CE313: "Xử lý song song và hệ thống phân tán",
    CE314: "Trình biên dịch",
    CE315: "Lập trình hệ thống với Java",
    CE316: "Logic mờ và ứng dụng",
    CE317: "Điều khiển tự động nâng cao",
    CE318: "Trình biên dịch",
    CE319: "Logic mờ và ứng dụng",
    CE321: "Kỹ thuật chế tạo vi mạch",
    CE322: "Thiết kế vi mạch hỗn hợp",
    CE323: "Kĩ thuật thiết kế mạch in",
    CE324: "Thiết kế vi mạch tương tự",
    CE325: "Thiết kế dựa trên vi xử lý",
    CE326: "Tự động hóa thiết kế vi mạch",
    CE327: "Tối ưu hóa dựa trên FPGA",
    CE331: "Kỹ thuật chế tạo vi mạch",
    CE332: "Thiết kế vi mạch hỗn hợp",
    CE333: "Tiếng Anh chuyên ngành Kỹ thuật Máy tính",
    CE334: "Thiết kế vi mạch tương tự",
    CE335: "Thiết kế dựa trên vi xử lý",
    CE336: "Tự động hóa thiết kế vi mạch",
    CE337: "Tối ưu hóa dựa trên FPGA",
    CE338: "Hệ thống thời gian thực",
    CE339: "Công nghệ IoT và Ứng dụng",
    CE340: "Trí tuệ nhân tạo cho hệ thống nhúng",
    CE341: "Lập trình nhúng trên các thiết bị di động",
    CE342: "Hệ thống thông minh",
    CE343: "Trí tuệ nhân tạo cho xe tự hành",
    CE344: "Trí tuệ nhân tạo cho IoT",
    CE345: "Kiến trúc IoT: Giao thức mạng và bảo mật",
    CE346: "Thiết kế Antenna tích hợp cho thiết bị IoT",
    CE401: "Kỹ thuật hệ thống máy tính",
    CE405: "Tương tác người máy",
    CE406: "Tương tác người-Máy",
    CE407: "Đồ án chuyên ngành Hệ thống nhúng và Robot",
    CE408: "Đồ án chuyên ngành Thiết kế vi mạch và phần cứng",
    CE409: "Kỹ thuật thiết kế kiểm tra",
    CE410: "Kỹ thuật hệ thống máy tính",
    CE411: "Chuyên đề hệ thống nhúng và robot",
    CE412: "Đồ án chuyên ngành Hệ thống nhúng và IoT",
    CE421: "Chuyên đề thiết kế vi mạch và phần cứng",
    CE430: "Lập trình hệ thống",
    CE432: "Thiết kế vi mạch hướng ASIC",
    CE433: "Thiết kế hệ thống SoC",
    CE434: "Chuyên đề thiết kế hệ vi mạch 1",
    CE435: "Chuyên đề thiết kế hệ vi mạch 2",
    CE436: "Xử lý tín hiệu số và ứng dụng",
    CE437: "Chuyên đề thiết kế hệ thống nhúng 1",
    CE438: "Chuyên đề thiết kế hệ thống nhúng 2",
    CE439: "Lập trình song song và hệ phân tán",
    CE501: "Thực tập doanh nghiệp",
    CE502: "Thực tập doanh nghiệp",
    CE505: "Khóa luận tốt nghiệp",
    CE506: "Luận văn chuyên sâu đặc thù",
    CNBU001: "Mạng máy tính",
    CNBU002: "Bảo mật",
    CNBU003: "Dự án nghiên cứu",
    CNBU004: "Thiết kế và phát triển website",
    CNBU005: "Internet of Things",
    CNBU006: "An toàn mạng máy tính",
    CNBU007: "Pháp chứng kỹ thuật số",
    CNBU008: "Quản lý an toàn thông tin",
    CNBU009: "Thực tập",
    CS005: "Giới thiệu ngành Khoa học Máy tính",
    CS105: "Đồ họa máy tính",
    CS106: "Trí tuệ nhân tạo",
    CS110: "Nhập môn công nghệ tri thức &amp; máy học",
    CS111: "Nguyên lý và phương pháp lập trình",
    CS1113: "Khoa học máy tính I",
    CS112: "Phân tích và thiết kế thuật toán",
    CS113: "Đồ họa máy tính và Xử lý ảnh",
    CS114: "Máy học",
    CS115: "Toán cho Khoa học máy tính",
    CS116: "Lập trình Python cho Máy học",
    CS117: "Tư duy tính toán",
    CS211: "Trí tuệ nhân tạo nâng cao",
    CS2133: "Khoa học máy tính II",
    CS214: "Biểu diễn tri thức và suy luận",
    CS217: "Các hệ cơ sở tri thức",
    CS221: "Xử lý ngôn ngữ tự nhiên",
    CS222: "Xử lý ngôn ngữ tự nhiên nâng cao",
    CS226: "Ngôn ngữ học máy tính",
    CS229: "Ngữ nghĩa học tính toán",
    CS231: "Nhập môn Thị giác máy tính",
    CS232: "Tính toán đa phương tiện",
    CS2433: "Lập trình C/C++",
    CS302: "Seminar",
    CS312: "Hệ thống đa tác tử",
    CS313: "Khai thác dữ liệu và ứng dụng",
    CS314: "Lập trình symbolic trong trí tuệ nhân tạo",
    CS315: "Máy học nâng cao",
    CS316: "Các hệ giải bài toán thông minh",
    CS321: "Ngôn ngữ học ngữ liệu",
    CS323: "Các hệ thống hỏi-đáp",
    CS324: "Máy học trong xử lý ngôn ngữ tự nhiên",
    CS325: "Dịch máy",
    CS326: "Các kĩ thuật trong xử lý ngôn ngữ tự nhiên",
    CS331: "Thị giác máy tính nâng cao",
    CS332: "Máy học trong Thị giác Máy tính",
    CS333: "Đồ họa game",
    CS335: "Tìm Kiếm Ảnh và Video",
    CS336: "Truy vấn thông tin đa phương tiện",
    CS3363: "Tổ chức ngôn ngữ lập trình",
    CS337: "Xử lý âm thanh và tiếng nói",
    CS3373: "Lập trình hướng đối tượng nâng cao cho môi trường windows",
    CS338: "Nhận dạng",
    CS339: "Xử lý văn bản Y khoa",
    CS3423: "Cấu trúc tập tin",
    CS3443: "Hệ thống máy tính",
    CS3613: "Cơ sở tính toán",
    CS3653: "Toán rời rạc cho máy tính",
    CS405: "Logic mờ và ứng dụng",
    CS406: "Xử lý ảnh và ứng dụng",
    CS409: "Hệ suy diễn mờ",
    CS410: "Mạng neural và thuật giải di truyền",
    CS412: "Web ngữ nghĩa",
    CS414: "Lý thuyết automat và ứng dụng",
    CS4143: "Đồ họa máy tính",
    CS4153: "Phát triển ứng dụng trên di động",
    CS417: "Nhận dạng",
    CS419: "Truy xuất thông tin",
    CS420: "Các vấn đề chọn lọc trong Thị giác máy tính",
    CS4243: "Thuật toán và tiến trình trong an toàn máy tính",
    CS4273: "Nhập môn Công nghệ phần mềm",
    CS4283: "Mạng máy tính",
    CS431: "Các kĩ thuật học sâu và ứng dụng",
    CS4323: "Hệ điều hành",
    CS4343: "Cấu trúc dữ liệu và giải thuật",
    CS4793: "Trí tuệ nhân tạo",
    CS5000: "Luận văn",
    CS5030: "Thực tập tốt nghiệp",
    CS505: "Khoá luận tốt nghiệp",
    CS511: "Ngôn ngữ lập trình C#",
    CS519: "Phương pháp luận nghiên cứu khoa học",
    CS521: "Toán rời rạc nâng cao",
    CS522: "Đại số máy tính",
    CS523: "Cấu trúc dữ liệu và giải thuật nâng cao",
    CS524: "Một số ứng dụng của xử lý ngôn ngữ tự nhiên",
    CS525: "Thị giác máy tính trong tương tác người – máy",
    CS526: "Phát triển ứng dụng đa phương tiện trên thiết bị di động",
    CS527: "Thực tại ảo",
    CS528: "Trực quan hóa thông tin",
    CS529: "Các vấn đề nghiên cứu và ứng dụng trong khoa học máy tính",
    CS530: "Đồ án chuyên ngành",
    CS532: "Thị giác máy tính trong tương tác người-máy",
    CS534: "Lập trình Javascript và ứng dụng",
    CS535: "Tổng hợp tiếng nói",
    CS5423: "Nguyên lý các hệ cơ sở dữ liệu",
    CS5433: "Các hệ cơ sở dữ liệu phân tán",
    CS551: "Thực tập",
    CSBU001: "Lập trình",
    CSBU002: "Mạng máy tính",
    CSBU003: "Thực hành nghề nghiệp",
    CSBU004: "Toán cho Tin học",
    CSBU005: "Bảo mật",
    CSBU006: "Quản lý dự án máy tính thành công",
    CSBU007: "Thiết kế và phát triển cơ sở dữ liệu",
    CSBU008: "Kiến trúc máy tính",
    CSBU009: "Dự án nghiên cứu",
    CSBU010: "Công nghệ kinh doanh thông minh",
    CSBU011: "Toán rời rạc",
    CSBU012: "Cấu trúc dữ liệu và giải thuật",
    CSBU013: "Lập trình nâng cao",
    CSBU014: "Máy học",
    CSBU015: "Điện toán đám mây",
    CSBU016: "Thực tập",
    CU001: "Văn hóa doanh nghiệp Nhật",
    DS005: "Giới thiệu ngành Khoa học Dữ liệu",
    DS101: "Thống kê và xác suất chuyên sâu",
    DS102: "Học máy thống kê",
    DS103: "Thu thập và tiền xử lý dữ liệu",
    DS104: "Tính toán song song &amp; phân tán",
    DS105: "Phân tích và trực quan dữ liệu",
    DS106: "Tối ứu hoá và ứng dụng",
    DS200: "Phân tích dữ liệu lớn",
    DS201: "Deep Learning trong khoa học dữ liệu",
    DS202: "Đồ án khoa học dữ liệu và ứng dụng 1",
    DS203: "Đồ án khoa học dữ liệu và ứng dụng 2",
    DS204: "Đồ án khoa học dữ liệu và ứng dụng",
    DS300: "Hệ khuyến nghị",
    DS301: "Các giải thuật khai phá dữ liệu lớn",
    DS302: "Phân tích thống kê đa biến",
    DS303: "Thống kê Bayes",
    DS304: "Thiết kế và phân tích thực nghiệm",
    DS305: "Phân tích dữ liệu chuỗi thời gian và ứng dụng",
    DS306: "Phân tích dữ liệu lớn trong tài chính",
    DS307: "Phân tích dữ liệu truyền thông xã hội",
    DS308: "Mô hình đồ thị xác suất",
    DS309: "Thực tập doanh nghiệp",
    DS310: "Xử lý ngôn ngữ tự nhiên cho Khoa học dữ liệu",
    DS505: "Khóa luận tốt nghiệp",
    EC001: "Kinh tế học đại cương",
    EC002: "Quản trị doanh nghiệp",
    EC003: "Tiếp thị căn bản",
    EC005: "Giới thiệu ngành Thương mại Điện tử",
    EC201: "Phân tích thiết kế quy trình nghiệp vụ doanh nghiệp",
    EC208: "QuẢN trị dự án TMĐT",
    EC213: "Quản trị quan hệ khách hàng và nhà cung cấp",
    EC214: "Nhập môn Quản trị chuỗi cung ứng",
    EC222: "Thực tập doanh nghiệp",
    EC229: "Pháp luật trong thương mại điện tử",
    EC232: "Nguyên lý kế toán",
    EC311: "Tiếp thị trực tuyến",
    EC312: "Thiết kế hệ thống thương mại điện tử",
    EC331: "Quản trị chiến lược kinh doanh điện tử",
    EC332: "Quản trị sản xuất",
    EC333: "Quản trị tài chính doanh nghiệp",
    EC334: "Quản trị kênh phân phối",
    EC335: "An toàn và bảo mật thương mại điện tử",
    EC336: "Quản trị nhân lực",
    EC337: "Hệ thống thanh toán trực tuyến",
    EC338: "Quản trị bán hàng",
    EC401: "Khóa luận tốt nghiệp",
    "EN001.CO": "English for Communication 1",
    "EN001.GE": "General English",
    "EN002.CO": "English for Communication 1",
    "EN002.GE": "General English",
    ENG01: "Anh văn 1",
    ENG02: "Anh văn 2",
    ENG03: "Anh văn 3",
    ENG04: "Anh văn 4",
    ENG05: "Anh văn 5",
    ENG06: "Kỹ năng thuyết trình tiếng Anh",
    ENG07: "Kỹ năng viết tiếng Anh",
    ENGA1: "Anh văn sơ cấp 1",
    ENGA2: "Anh văn sơ cấp 2",
    ENGL1113: "Tiếng Anh I",
    ENGL1213: "Tiếng Anh II",
    IE005: "Giới thiệu ngành Công nghệ Thông tin",
    IE101: "Cơ sở hạ tầng công nghệ thông tin",
    IE102: "Các công nghệ nền",
    IE103: "Quản lý thông tin",
    IE104: "Internet và công nghệ Web",
    IE105: "Nhập môn bảo đảm và an ninh thông tin",
    IE106: "Thiết kế giao diện người dùng",
    IE201: "Xử lý dữ liệu thống kê",
    IE202: "Quản trị doanh nghiệp",
    IE203: "Hệ thống quản trị qui trình nghiệp vụ",
    IE204: "Tối ưu hóa công cụ tìm kiếm",
    IE205: "Xử lý ảnh vệ tinh",
    IE206: "Đồ án chuẩn bị tốt nghiệp",
    IE207: "Đồ án",
    IE209: "Công nghệ Java",
    IE212: "Công nghệ Dữ liệu lớn",
    IE213: "Kỹ thuật phát triển hệ thống Web",
    IE216: "Các chủ đề toán học cho KHDL",
    IE218: "Xử lý dữ liệu lớn",
    IE221: "Kỹ thuật lập trình Python",
    IE223: "Phân tích dữ liệu bằng Python &amp;R",
    IE224: "Phân tích dữ liệu",
    IE225: "Interconnections Networks",
    IE226: "Computer Graphics and Visualization",
    IE227: "Signal Processing over Networks",
    IE228: "Human-Computer Interaction",
    IE229: "Artificial Intelligence",
    IE230: "Viết báo cáo kỹ thuật bằng tiếng Nhật",
    IE301: "Quản trị quan hệ khách hàng",
    IE302: "Kiến trúc và tích hợp hệ thống",
    IE303: "Công nghệ Java",
    IE304: "Hệ thống định vị toàn cầu",
    IE305: "Tin học môi trường",
    IE307: "Công nghệ lập trình đa nền tảng cho ứng dụng di động",
    IE309: "Thực tập doanh nghiệp",
    IE401: "Tin-Sinh học",
    IE402: "Hệ thống thông tin địa lý 3 chiều",
    IE403: "Khai thác dữ liệu truyền thông xã hội",
    IE405: "Công nghệ phân tích dữ liệu lớn",
    IE406: "Nhập môn ẩn thông tin và ứng dụng",
    IE505: "Khóa luận tốt nghiệp",
    IEM4733: "Tái cấu trúc quy trình doanh nghiệp",
    IEM5723: "Mô hình hóa dữ liệu, quy trình và đối tượng",
    INT001: "Tiếng Anh tổng quát (tạm gọi)",
    INT002: "Toeic 1",
    INT003: "Tiếng Anh tổng quát 2 (tạm gọi)",
    INT004: "Toeic 2",
    INT005: "Tiếng Anh giao tiếp (tạm gọi)",
    INT006: "Toeic 3",
    IS005: "Giới thiệu ngành Hệ thống Thông tin",
    IS105: "Hệ quản trị cơ sở dữ liệu Oracle",
    IS201: "Phân tích thiết kế hệ thống thông tin",
    IS207: "Phát triển ứng dụng web",
    IS208: "Quản lý dự án công nghệ thông tin",
    IS210: "Hệ quản trị cơ sở dữ liệu",
    IS211: "Cơ sở dữ liệu phân tán",
    IS212: "Thực tập tốt nghiệp",
    IS215: "Thiết kế hướng đối tượng với UML",
    IS216: "Lập trình Java",
    IS217: "Kho dữ liệu và OLAP",
    IS220: "Xây dựng HTTT trên các framework",
    IS232: "Hệ thống thông tin kế toán",
    IS251: "Nhập môn Hệ thống thông tin địa lý",
    IS252: "Khai thác dữ liệu",
    IS254: "Hệ hỗ trợ quyết định",
    IS311: "Đồ án xây dựng hệ thống thông tin",
    IS332: "Hệ thống thông tin quản lý",
    IS334: "Thương mại điện tử",
    IS335: "An toàn và bảo mật hệ thống thông tin",
    IS336: "Hoạch định nguồn lực doanh nghiệp",
    IS339: "Sinh tin học",
    IS340: "Thị trường chứng khoán",
    IS341: "Khởi nghiệp",
    IS342: "Chính phủ điện tử",
    IS351: "Phân tích không gian",
    IS352: "Hệ cơ sở dữ liệu không gian",
    IS353: "Mạng xã hội",
    IS401: "Khóa luận tốt nghiệp",
    IS402: "Điện toán đám mây",
    IS403: "Phân tích dữ liệu kinh doanh",
    IS405: "Dữ liệu lớn",
    IS502: "Thực tập doanh nghiệp",
    IS505: "Khóa luận tốt nghiệp",
    IT001: "Nhập môn lập trình",
    IT002: "Lập trình hướng đối tượng",
    IT003: "Cấu trúc dữ liệu và giải thuật",
    IT004: "Cơ sở dữ liệu",
    IT005: "Nhập môn mạng máy tính",
    IT006: "Kiến trúc máy tính",
    IT007: "Hệ điều hành",
    IT008: "Lập trình trực quan",
    IT009: "Giới thiệu ngành",
    IT010: "Tổ chức và cấu trúc máy tính",
    IT011: "Nhập môn lập trình thi đấu",
    IT012: "Tổ chức và Cấu trúc Máy tính II",
    IT013: "Cấu trúc dữ liệu cho lập trình thi đấu",
    ITNT005: "Communication",
    JAN01: "Tiếng Nhật 1",
    JAN02: "Tiếng Nhật 2",
    JAN03: "Tiếng Nhật 3",
    JAN04: "Tiếng Nhật 4",
    JAN05: "Tiếng Nhật 5",
    JAN06: "Tiếng Nhật 6",
    JAN07: "Tiếng Nhật 7",
    JAN08: "Tiếng Nhật 8",
    MA003: "Đại số tuyến tính",
    MA004: "Cấu trúc rời rạc",
    MA005: "Xác suất thống kê",
    MA006: "Giải tích",
    MATH2144: "Giải tích I",
    MATH2153: "Giải tích II",
    MATH3013: "Đại số tuyến tính",
    ME001: "Giáo dục quốc phòng",
    MEDU1: "Giáo dục quốc phòng",
    MKTG4223: "Quản trị chuỗi cung ứng",
    MKTG5883: "Khai phá dữ liệu và ứng dụng",
    MSIS207: "Phát triển ứng dụng web",
    MSIS2433: "Lập trình hướng đối tượng",
    MSIS3033: "Quản lý dự án hệ thống thông tin",
    MSIS3233: "Management Science Methods",
    MSIS3242: "Sofware Quality Management",
    MSIS3243: "Managerial Decision Theory",
    MSIS3303: "Phân tích thiết kế hệ thống",
    MSIS4013: "Thiết kế, quản lý và quản trị hệ CSDL",
    MSIS402: "Điện toán đám mây",
    MSIS405: "Dữ liệu lớn",
    MSIS4133: "Công nghệ thông tin trong thương mại điện tử",
    MSIS4243: "Control and Audit of Information Systems",
    MSIS4263: "Các ứng dụng thông minh và hỗ trợ ra quyết định",
    MSIS4443: "Các hệ thống mô phỏng trên máy tính",
    MSIS4523: "Hệ truyền thông dữ liệu",
    NHJP1: "Tiếng Nhật Sơ cấp 1",
    NHJP2: "Tiếng Nhật Sơ cấp 2",
    NT005:"Giới thiệu ngành Mạng máy tính và Truyền thông dữ liệu",
    NT015: "Giới thiệu ngành An toàn Thông tin",
    NT101: "An toàn mạng máy tính",
    NT103: "Hệ điều hành Linux",
    NT104: "Lý thuyết thông tin",
    NT105: "Truyền dữ liệu",
    NT106: "Lập trình mạng căn bản",
    NT109: "Lập trình ứng dụng mạng",
    NT111: "Thiết bị mạng và truyền thông ĐPT",
    NT113: "Thiết kế Mạng",
    NT114: "Đồ án chuyên ngành",
    NT115: "Thực tập doanh nghiệp",
    NT117: "Đồ án môn học Lập trình ứng dụng Mạng",
    NT118: "Phát triển ứng dụng trên thiết bị di động",
    NT121: "Thiết bị mạng và truyền thông ĐPT",
    NT131: "Hệ thống nhúng Mạng không dây",
    NT132: "Quản trị mạng và hệ thống",
    NT133: "An toàn kiến trúc hệ thống",
    NT137: "Kỹ thuật phân tích mã độc",
    NT201: "Phân tích thiết kế hệ thống truyền thông và mạng",
    NT204: "Hệ thống tìm kiếm, phát hiện và ngăn ngừa xâm nhập",
    NT205: "Tấn công mạng",
    NT207: "Quản lý rủi ro và an toàn thông tin trong doanh nghiệp",
    NT208: "Lập trình ứng dụng Web",
    NT209: "Lập trình hệ thống",
    NT210: "Thương mại Điện tử và Triển khai ứng dụng",
    NT211: "An ninh nhân sự, định danh và chứng thực",
    NT212: "An toàn dữ liệu, khôi phục thông tin sau sự cố",
    NT213: "Bảo mật web và ứng dụng",
    NT215: "Thực tập doanh nghiệp",
    NT216: "Bảo mật hệ thống dữ liệu",
    NT219: "Mật mã học",
    NT230: "Cơ chế hoạt động của mã độc",
    NT303: "Công nghệ thoại IP",
    NT310: "Pháp chứng mạng di động",
    NT311: "Công nghệ tường lửa và bảo vệ mạng ngoại vi",
    NT312: "Bảo mật với smartcard và NFC",
    NT330: "An toàn mạng không dây và di động",
    NT331: "Xây dựng chuẩn chính sách an toàn thông tin trong doanh nghiệp",
    NT332: "Xử lý tín hiệu trong truyền thông",
    NT333: "Tính toán lưới",
    NT334: "Pháp chứng kỹ thuật số",
    NT402: "Công nghệ mạng viễn thông",
    NT405: "Bảo mật Internet",
    NT406: "Đồ án tốt nghiệp",
    NT504: "Tiểu luận tốt nghiệp",
    NT505: "Khóa luận tốt nghiệp",
    NT521: "Lập trình an toàn và khai thác lỗ hổng phần mềm",
    NT522: "Phương pháp học máy trong an toàn thông tin",
    NT523: "An toàn thông tin trong kỷ nguyên máy tính lượng tử",
    NT531: "Đánh giá hiệu năng hệ thống mạng máy tính",
    NT532: "Công nghệ Internet of things hiện đại",
    NT533: "Hệ tính toán phân bố",
    NT534: "An toàn mạng máy tính nâng cao",
    NT535: "Bảo mật Internet of things",
    NT536: "Công nghệ truyền thông đa phương tiện",
    NT537: "Truyền thông xã hội và kinh doanh",
    NT538: "Giải thuật xử lý song song và phân bố",
    NT539: "AI ứng dụng trong mạng và truyền thông",
    PE002: "Giáo dục thể chất 2",
    PE012: "Giáo dục thể chất",
    PH001: "Nhập môn điện tử",
    PH002: "Nhập môn mạch số",
    PHYS1114: "Vật lý đại cương I",
    PHYS1214: "Vật lý đại cương II",
    SC203: "Phương pháp khoa học",
    SE005: "Giới thiệu ngành Kỹ thuật Phần mềm",
    SE100: "Phương pháp Phát triển phần mềm hướng đối tượng",
    SE101: "Phương pháp mô hình hóa",
    SE102: "Nhập môn phát triển game",
    SE104: "Nhập môn Công nghệ phần mềm",
    SE106: "Đặc tả hình thức",
    SE109: "Phát triển, vận hành, bảo trì phần mềm",
    SE111: "Đồ án mã nguồn mở",
    SE112: "Đồ án chuyên ngành",
    SE113: "Kiểm chứng phần mềm",
    SE114: "Nhập môn ứng dụng di động",
    SE121: "Đồ án 1",
    SE122: "Đồ án 2",
    SE214: "Công nghệ phần mềm chuyên sâu",
    SE215: "Giao tiếp người máy",
    SE220: "Thiết kế Game",
    SE221: "Lập trình game nâng cao",
    SE301: "Phát triển phần mềm mã nguồn mở",
    SE310: "Công nghệ .NET",
    SE313: "Một số thuật toán thông minh",
    SE320: "Lập trình đồ họa 3 chiều với Direct3D",
    SE325: "Chuyên đề J2EE",
    SE327: "Phát triển và vận hành game",
    SE328: "Lập trình TTNT trong Game",
    SE329: "Thiết kế 3D Game Engine",
    SE330: "Ngôn ngữ lập trình Java",
    SE331: "Chuyên đề E-commerce",
    SE332: "Chuyên đề CSDL nâng cao",
    SE334: "Các phương pháp lập trình",
    SE340: "Quản lý dự án công nghệ thông tin",
    SE341: "Công nghệ Web và ứng dụng",
    SE343: "Công nghệ Portal",
    SE344: "Lập trình game trong các thiết bị di động",
    SE346: "Lập trình trên thiết bị di động",
    SE347: "Công nghệ Web và ứng dụng",
    SE348: "Chuyên đề M-commerce",
    SE350: "Chuyên đề E-learning",
    SE351: "Xử lý song song",
    SE352: "Phát triển ứng dụng VR",
    SE354: "Chuyên đề các quy trình phát triển phần mềm hiện đại",
    SE355: "Máy học và các công cụ",
    SE356: "Kiến trúc Phần mềm",
    SE357: "Kỹ thuật phân tích yêu cầu",
    SE358: "Quản lý dự án Phát triển Phần mềm",
    SE400: "Seminar các vấn đề hiện đại của CNPM",
    SE401: "Mẫu thiết kế",
    SE403: "Nguyên lý thiết kế thế giới ảo",
    SE404: "Chuyên đề E-Government",
    SE405: "Chuyên đề Mobile and Pervasive Computing",
    SE417: "Đồ án môn học mã nguồn mở",
    SE501: "Thực tập tốt nghiệp",
    SE505: "Khóa luận tốt nghiệp",
    SPCH2713: "Kỹ năng giao tiếp",
    SPCH3723: "Tiếng Anh chuyên ngành CNTT",
    SPCH3724: "Kỹ năng giao tiếp",
    SS003: "Tư tưởng Hồ Chí Minh",
    SS004: "Kỹ năng nghề nghiệp",
    SS006: "Pháp luật đại cương",
    SS007: "Triết học Mác-Lênin",
    SS008: "Kinh tế chính trị Mác-Lênin",
    SS009: "Chủ nghĩa xã hội khoa học",
    SS010: "Lịch sử Đảng Cộng sản Việt Nam",
    STAT3013: "Phân tích thống kê",
    STAT4033: "Thống kê",
    "TOEIC 450": "TOEIC 450",
    TOEIC450: "TOEIC 450",
}

export default LessonCode;